### ISSUE TITLE
Change tab icon

### ISSUE THREAD

**Issue by igords-goncalves** [igords-goncalves/apuracoes-app#6]
Currently tab icon used is that default of React. I wanna change it and put something with the same purpose of the application, something about Brazilian elections.

![image](https://user-images.githubusercontent.com/79734585/198298424-3983ca37-38a6-49fe-8ad7-3191cf8b0e5a.png)

I was thinking that it's also better change title to Portuguese once the application is in the Portuguese language. 

![image](https://user-images.githubusercontent.com/79734585/198300165-c4b700ed-01f3-474b-89d2-deecdf106968.png)

Here you are some suggestions

- pt_br = Resultados das Eleições
- pt_br = Eleições Brasileira
- pt_br = Apurações

**Comment by Jaqueline-17** [comment]
oi tudo bem, voce consegue mudar isso na pasta index html que já vem no react, onde fica a div root a sintaxe é  <link rel="icon" href="link da imagem">
espero ter ajudado

**Comment by igords-goncalves** [comment]
> oi tudo bem, voce consegue mudar isso na pasta index html que já vem no react, onde fica a div root a sintaxe é "" espero ter ajudado

Eu sei o "print" já mostra isso, mas deixei aberto para a galera praticar, enviar alguns Pull-requests e ver que colaborar não é um bicho de 7 cabeças!

**Comment by igords-goncalves** [comment]
New icon

![image](https://user-images.githubusercontent.com/79734585/199787100-ed9a094c-441b-4ed9-86d8-e17b6a22ab0f.png)

**Comment by igords-goncalves** [comment]
New icon

![image](https://user-images.githubusercontent.com/79734585/199787100-ed9a094c-441b-4ed9-86d8-e17b6a22ab0f.png)

**Comment by igords-goncalves** [comment]
New icon

![image](https://user-images.githubusercontent.com/79734585/199787100-ed9a094c-441b-4ed9-86d8-e17b6a22ab0f.png)
